apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api-gateway-app
  namespace: default
  labels:
    app:  api-gateway-app
spec:
  selector:
    matchLabels:
      app: api-gateway-app
  replicas: 1
  template:
    metadata:
      labels:
        app:  api-gateway-app
    spec:
      containers:
      - name:  api-gateway-app
        image:  ajithkrkd/planb-api-gateway:0.0.1
        imagePullPolicy: Always 
        resources:
          requests:
            cpu: 100m
            memory: 251Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
          - name: EUREKA.CLIENT.SERVICEURL.DEFAULTZONE
            value: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
          - name: MANAGEMENT.ZIPKIN.TRACING.ENDPOINT
            value: http://zipkin:9411/
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service-svc
spec:
  selector:
    app: api-gateway-app
  type: NodePort
  ports:
  - port: 80  
    targetPort: 8080  
    nodePort: 32000
    protocol: TCP
  

        