apiVersion: apps/v1
kind: Deployment
metadata:
  name:  notification-service-app
  namespace: default
  labels:
    app:  notification-service-app
spec:
  selector:
    matchLabels:
      app: notification-service-app
  replicas: 1
  template:
    metadata:
      labels:
        app:  notification-service-app
    spec:
      containers:
      - name:  notification-service-app
        image:  ajithkrkd/planb-notification-service:0.0.1
        imagePullPolicy: Always 
        resources:
          requests:
            cpu: 100m
            memory: 251Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
          - name: EUREKA.CLIENT.SERVICEURL.DEFAULTZONE
            value: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
          - name: MANAGEMENT.ZIPKIN.TRACING.ENDPOINT
            value: http://zipkin:9411/
          - name: SPRING.KAFKA.BOOTSTRAP-SERVERS
            value: broker:29092
        ports:
        - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-svc
spec:
  selector:
    app: notification-service-app
  type: ClusterIP
  ports:
    - port:  80
      targetPort: 8083
  

        